
keyvalue.v: keyvalue.py
	./keyvalue.py 16 16 8 1 keyvalue_1 > keyvalue_1.v
	./keyvalue.py 7 7 4 1 keyvalue_2 > keyvalue_2.v
	./keyvalue.py 16 16 32 1 keyvalue_3 > keyvalue_3.v
	./keyvalue.py 7 7 8 32 keyvalue_4 > keyvalue_4.v

clean:
	rm keyvalue.v

test:
	echo "no test yet"
