
keyvalue.v: keyvalue.py
	./keyvalue.py 16 16 32 1 keyvalue_1 > keyvalue_1.v
	./keyvalue.py 8 8 12 1 keyvalue_2 > keyvalue_2.v
	./keyvalue.py 64 64 128 1 keyvalue_3 > keyvalue_3.v
	./keyvalue.py 4 4 16 1 keyvalue_4 > keyvalue_4.v


clean:
	rm keyvalue.v

test:
	echo "no test yet"
